[tool.poetry]
name = "airflow"
version = "0.1.0"
description = ""
authors = ["Ethan Leifer <ethanleifer@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10"
pandas = "^1.5.2"
pycoingecko = "^3.1.0"

[tool.poetry.group.dev.dependencies]
apache-airflow = "^2.5.0"
apache-airflow-providers-postgres = "^5.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
