version: '3'

services:
  bread:
    build:
      context: .
      dockerfile: Dockerfile.bread
    ports:
      - "3000:3000"
      - "3456:3456"
      - "5433:5433"
      - "8080:8080"
    volumes:
      - .:/app
