version: '3'
services:
  redis-mono:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    volumes:
        - redis_data:/data
  postgres:
    image: postgres:15
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080
volumes:
  redis_data:
  postgres-db-volume:
