version: '3'
services:
  postgres:
    image: postgres:14
    container_name: workhorse # suppose to mirror our prod workhorse setup essentially
    ports: 
      - 5431:5431
    expose: 
      - 5431
    env_file: 
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    command: -p 5431 # runs postgres on a different port
volumes:
  postgres-db-volume:
networks:
  default: 
    name: sn-mono-network
    driver: bridge