[tool.poetry]
name = "sn-mono"
version = "0.1.0"
description = ""
authors = ["Ethan Leifer <ethanleifer@gmail.com>"]
readme = "README.md"
packages = [{include = "sn_mono"}]

[tool.poetry.dependencies]
python = "^3.11"
dashboard = { path = "./packages/dashboard", develop = true }
black = "^22.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
