version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api
    platform: linux/arm64
    ports:
      - "4000:4000"
    env_file:
      - .env
      - ./../../.env
    volumes:
      - ./api:/api
networks:
  default:
    name: sn-mono-network
    driver: bridge
    external: true
