version: '3'
services:
  api: 
    container_name: sn-api
    build: 
        context: .
        dockerfile: Dockerfile
    platform: linux/arm64
    ports:
      - "4000:4000"
    env_file:
      - .env
      - ./../../.env
    command: uvicorn main:app --host 0.0.0.0 --port 4000 --reload
networks:
  default:
    name: sn-mono-network
    driver: bridge
    external: true