[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Ethan Leifer <ethanleifer@gmail.com>"]

[tool.poetry.dependencies]
python = "3.10.*"
fastapi = "^0.89.1"
uvicorn = {version = "^0.20.0", extras = ["standard"]}
python-dotenv = "^1.0"
databases = {version = "^0.7.0", extras = ["asyncpg"]}
gunicorn = "^20.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
