services:
  dagster:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dagster
    volumes:
      - ./dags:/dags/dags
      - ./dagster_home:/dags/dagster_home
      - ./dbt_project:/dags/dbt_project
      - $GOOGLE_APPLICATION_CREDENTIALS:/dags/creds.json
    ports:
      - ${DAGSTER_PORT}:${DAGSTER_PORT}
    env_file:
      - ./../../.env
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./creds.json
    command: poetry run dagster dev -p ${DAGSTER_PORT} -h 0.0.0.0
networks:
  default:
    name: sn-mono-network
    driver: bridge
    external: true
