[tool.poetry]
name = "dags"
version = "0.1.0"
description = ""
authors = ["Ethan Leifer <ethanleifer@gmail.com>"]

[tool.poetry.dependencies]
python = "3.10.*"
dagster = "1.3.1"
dagit = "1.3.1"
dbt-core = "^1.4.5"
dbt-postgres = "^1.4.5"
dagster-dbt = "0.19.1"
pandas = "^2.0.0"
pycoingecko = "^3.1.0"
dagster-gcp = "^0.19.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.dagster]
module_name = "dags"
