name: Dbt Tests

on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  dbt-tests:

      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
          - name: Docker Compose Run Tests
            working-directory: packages/dbt-indexer
            run: docker compose -f docker-compose.yaml -f docker-compose.tests.yaml run dbt