version: '3'
x-common-variables:
  &common-variables
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres
  - POSTGRES_DB=postgres
  - POSTGRES_PORT=5430
  - POSTGRES_HOST=test_postgres
  - INDEXER_SCHEMA=tests
  - BUCKET_NAME=sn-mono-indexer-tests
  - GOOGLE_APPLICATION_CREDENTIALS=./creds.json
  - GOOGLE_CLOUD_PROJECT=${GCP_PROJECT_ID}
services:
  indexer-test:
    image: indexer
    build:
      context: .
      dockerfile: Dockerfile
    command: pytest --junitxml=pytest.xml --cov="indexer" --cov-report=xml --cov-report term-missing --cov-fail-under=85 -vvv
    depends_on:
      - test_postgres
    environment: *common-variables
    volumes:
      - .:/indexer
      - $GOOGLE_APPLICATION_CREDENTIALS:/indexer/creds.json
    container_name: indexer-test
  test_postgres:
    image: postgres:14
    container_name: test-postgres
    environment: *common-variables
    ports:
      - 5430:5430
    expose:
      - 5430
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    command: -p 5430 # runs postgres on a different por
