version: '3'
services:
  indexer:
    image: gcr.io/secretnetwork/sn-mono/{GIT_BRANCH}/{GIT_BRANCH}-indexer:latest
    env_file:
      - .env
      - ./../../.env
    volumes:
      - ./:/indexer
    container_name: indexer
    command: python indexer/main.py
    working_dir: /indexer
