version: '3'
services:
  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    image: indexer-prod
    container_name: indexer
    command: python indexer/main.py
    working_dir: /indexer
