version: '3'
services:
  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    image: indexer
    container_name: ${COMPOSE_PREFIX}-indexer
networks:
  default:
    name: sn-mono-network
    driver: bridge
    external: true
