version: '3'
services:
  indexer:
    environment:
      - POSTGRES_HOST=test_postgres
      - POSTGRES_PORT=5430
    command: pytest --cov="indexer" --cov-report=term-missing tests/ -vvv
  test_postgres:
    image: postgres:14
    container_name: test_postgres # suppose to mirror our prod workhorse setup essentially
    ports:
      - 5430:5430
    expose:
      - 5430
    env_file:
      - ./../../.env
    environment:
      - POSTGRES_HOST=test_postgres
      - POSTGRES_PORT=5430
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    command: -p 5430 # runs postgres on a different port
