version: '3'
services:
  indexer-live:
    image: indexer-dev
    env_file:
      - .env
      - ./../../.env
    volumes:
      - ./:/indexer
  indexer-backfill:
    image: indexer-dev
    env_file:
      - .env
      - ./../../.env
    volumes:
      - ./:/indexer
networks:
  default:
    name: sn-mono-network
    driver: bridge
    external: true
