version: '3'
services:
  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    image: indexer-dev
    env_file:
      - .env
      - ./../../.env
    volumes:
      - ./:/indexer
networks:
  default:
    name: sn-mono-network
    driver: bridge
    external: true
