[tool.poetry]
name = "indexer"
version = "0.1.0"
description = ""
authors = ["Ethan Leifer <ethanleifer@gmail.com>"]

[tool.poetry.dependencies]
python = "3.10.*"
asyncio = "^3.4.3"
python-dotenv = "^1.0"
aiohttp = "^3.8.3"
aiodns = "^3.0.0"
asyncpg = "^0.27.0"
pandas = "^2.0"
deepdiff = "^6.3.0"
google-cloud-storage = "^2.8.0"
aiofiles = "^23.1.0"
parse = { path = "./../parse", develop = true }
pytest = "^7.2.2"
pytest-asyncio = "^0.20.3"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"
line-profiler = "^4.0.3"
gcloud-aio-storage = "^8.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode="auto"
pythonpath="."