[tool.poetry]
name = "indexer"
version = "0.1.0"
description = ""
authors = ["Ethan Leifer <ethanleifer@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.*"
asyncio = "^3.4.3"
python-dotenv = "^0.21.1"
aiohttp = "^3.8.3"
aiodns = "^3.0.0"
asyncpg = "^0.27.0"
pandas = "^1.5.3"
asyncpg-listen = "^0.0.6"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
pytest-asyncio = "^0.20.3"
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
